### ISSUE TITLE
Search results component creation

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/header-rgm#2]
**UI Component**
- [x] Create new folder `search-results` under UI area
https://github.com/rakuten-rex/header-rgm/tree/feature/search-results/src/components/ui

- [x] Create wrapper component as `SearchResults`
- [x] Create `Item` component with props:
- href
- type (Single, InCategory, InShop)
- Name
- Category (it can be empty)

- [x] Create `ItemSingle` component
- [x] Create `ItemInCategory` component
- [x] Create `ItemInShop` component

- [x] Use `BodyText1`  component from `rex typography` to build `Name, Category and Location` components
```javascript
<BodyText1 tag='span'>
```
https://rakuten-rex.github.io/typography/?path=/story/typography-body-text--body-text1

- [x] Create `Name` component

- [x] Create `Category` component
- [x] Create `Location` component
- [x] Create `Separator` component

**Stories**

- [x] Create `SearchResults` story
- [x] Create `Item` story
- [x] Create `ItemSingle` story
- [x] Create `ItemInCategory` story
- [x] Create `ItemInStore` story
- [x] Create `Name` story
- [x] Create `Category` story
- [x] Create `Location` story
- [x] Create `Separator` story

**Comment by Kosukeee** [comment]
- [ ] Add knobs to Item (type)
- [ ] Add knobs to props other components (ItemInCategory, ItemInShop ...)

**Comment by Kosukeee** [comment]
- [ ] Modify class name (lowercase, dash)
- [ ] Add ...props
- [ ] Fix import BodyText1 (directly)
- [ ] Fix prop type (string, instead of node)
- [ ] Add types
- [ ] Link component display 'block' (item)
- [ ] Add knobs to SearchResults (listData object, also try array)
- [ ] Change listData to add inStore key(boolean)
- [ ] Add logic for separator (only if inStore is true)

**Comment by Kosukeee** [comment]
- [ ] Add another SearchResults story, add number (ex, 10) to add sample(Single, inCategory)

- [ ] Fix figma stylem (line-height, colors)

- [ ] Fix decoded name in all stories

**Comment by claudio-moya** [comment]
- [ ] If there are no parameters `<SearchResults />` should return `null` instead of `map` error

- [ ] If the listData is an empty object `<SearchResults listData={{}} />` should return `null` instead of `map` error

**Comment by claudio-moya** [comment]
- [ ] Add `inStore` boolean option in `ui-components-searchresults--searchresults-multiple-lists`

**Comment by claudio-moya** [comment]
Components
- [ ] Rename folder `src/components/ui/search-results` to `src/components/ui/SearchResults`

- [ ] Add `index.jsx` and export `SearchResults.jsx` in `src/components/ui/SearchResults`

- [ ] Rename folder  `src/components/ui/search-results/items` to `src/components/ui/SearchResults/Item`

- [ ] Move `src/components/ui/SearchResults/Item.jsx` to `src/components/ui/SearchResults/Item`

- [ ] Add `src/components/ui/SearchResults/Item.jsx` to `index.jsx`

Stories
- [ ] Rename `stories/ui/SearchResults/Components` to `stories/ui/SearchResults/components`

- [ ] Move `stories/ui/SearchResults.jsx` to `stories/ui/` as `stories/ui/index.jsx`

**Comment by claudio-moya** [comment]
- [ ] Update prop types of `SearchResults` to:
```
  list: shape({
    inStore: bool,
    resultList: arrayOf(object),
  }),
```

**Comment by claudio-moya** [comment]
Component
- [ ] Fix duplicated name of `list` from params and `forEach`
https://github.com/rakuten-rex/header-rgm/blob/ac761671eb0517bbd2b8660a047d2ac2d5c48c12/src/components/ui/SearchResults/SearchResults.jsx#L12
https://github.com/rakuten-rex/header-rgm/blob/ac761671eb0517bbd2b8660a047d2ac2d5c48c12/src/components/ui/SearchResults/SearchResults.jsx#L14

- [ ] Add missed `...props`
https://github.com/rakuten-rex/header-rgm/blob/ac761671eb0517bbd2b8660a047d2ac2d5c48c12/src/components/ui/SearchResults/Item/Item.jsx#L31

- [ ] Use `types` to replace `string` types
https://github.com/rakuten-rex/header-rgm/blob/ac761671eb0517bbd2b8660a047d2ac2d5c48c12/src/components/ui/SearchResults/Item/types.js#L1-L5
https://github.com/rakuten-rex/header-rgm/blob/ac761671eb0517bbd2b8660a047d2ac2d5c48c12/src/components/ui/SearchResults/Item/Item.jsx#L13
https://github.com/rakuten-rex/header-rgm/blob/ac761671eb0517bbd2b8660a047d2ac2d5c48c12/src/components/ui/SearchResults/Item/Item.jsx#L17
https://github.com/rakuten-rex/header-rgm/blob/ac761671eb0517bbd2b8660a047d2ac2d5c48c12/src/components/ui/SearchResults/Item/Item.jsx#L21
https://github.com/rakuten-rex/header-rgm/blob/ac761671eb0517bbd2b8660a047d2ac2d5c48c12/src/components/ui/SearchResults/Item/Item.jsx#L42

Stories

- [ ] Rename` stories/ui/SearchResults/Components` to `stories/ui/SearchResults/components` (lowercase)

**Comment by claudio-moya** [comment]
**Component**
- [ ] Change keys to uppercase like constants (SINGLE, IN_CATEGORY, IN_STORE)
https://github.com/rakuten-rex/header-rgm/blob/ac761671eb0517bbd2b8660a047d2ac2d5c48c12/src/components/ui/SearchResults/Item/types.js#L1-L5

- [ ] Story `/story/ui-components-searchresults--searchresults`  is not working

**Browserstack** 
UI tests (not screenshots) local testing
- [ ] Safari
- [ ] Firefox

- [ ] Chrome

- [ ] Edge

- [ ]  IE11 (to see how it looks)

**Browserstrack** 
Screenshots test
- [ ] http://localhost:8080/?path=/story/ui-components-searchresults--searchresults

- [ ] http://localhost:8080/?path=/story/ui-components-searchresults-components--category

- [ ] http://localhost:8080/?path=/story/ui-components-searchresults-components--location

- [ ] http://localhost:8080/?path=/story/ui-components-searchresults-components--name

- [ ] http://localhost:8080/?path=/story/ui-components-searchresults-components--separator

- [ ] Use 10 items and 10 categories
 http://localhost:8080/?path=/story/ui-components-searchresults--searchresults-multiple-lists
- [ ] Without `inShop`
 http://localhost:8080/?path=/story/ui-components-searchresults--searchresults-multiple-lists

**Comment by Kosukeee** [comment]
Finished screenshot test.

- Some iOS screenshot failed to take
- Couldn't take "Without inShop" screenshot

I didn't see any problems by checking screenshots.
