### ISSUE TITLE
Requires <button> tag instead and :hover, :active...state styles

### ISSUE THREAD

**Issue by montomos** [rakuten-rex/header-rgm#20]
https://github.com/rakuten-rex/header-rgm/blob/d3181f975398ff25b05b1d4f5eb4c8345108889a/src/ui/BeforeLogin/UserSignUp/PC/Menu.jsx#L19

**Comment by claudio-moya** [comment]
@montomos take a look to this one if is done or we have to fix it please

**Comment by montomos** [comment]
Please check feature/add-pcmenu-state branch.

**Comment by montomos** [comment]
@claudio-moya  Please check feature/add-pcmenu-state again.

**Comment by montomos** [comment]
@claudio-moya Let me know the details.

**Comment by claudio-moya** [comment]
thanx! merged into develop
