### ISSUE TITLE
Add support to form in Cart button

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/header-rgm#26]
- [x] Add form tag to Cart button including the hidden values, take the reference from production site
```html
<form action="https://global.rakuten.co.jp/cart/cartInfo.xhtml?_ra=1554958797176%7Cc3ddaee1-30c3-4208-9538-85c69dff32dd" method="post" id="cart-icon">
   <button type="submit" class="c-account__item c-account__item--cart"></button>
   <input type="hidden" name="i18n_currency" value="jpy">
   <input type="hidden" name="i18n_locale" value="en">
   <input type="hidden" name="i18n_country" value="aq">
</form>
```

**Comment by claudio-moya** [comment]
- [ ] Mobile implementation @Kosukeee (please share the code to @montomos after it's done)

- [ ] PC implementation @montomos

**Comment by Kosukeee** [comment]
@montomos -san,
Please replace this code
https://github.com/rakuten-rex/header-rgm/blob/0d0bb225a5c00db7f18155ad330eeb60acd2c96f/src/ui/Navigation/PC/MenuPC.jsx#L37-L41
to this
https://github.com/rakuten-rex/header-rgm/blob/0d0bb225a5c00db7f18155ad330eeb60acd2c96f/src/ui/Navigation/Mobile/MenuMobile/MenuMobile.jsx#L39-L48
