### ISSUE TITLE
Add missed 'points' text after points value

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/header-rgm#36]
App Settings
- [x] Add missed value in App Settings
Current
```
"afterLogin": {"greetings": "Hi"},
```

New
```
"afterLogin": {"greetings": "Hi": "pointsText": "points"},
```
Component
- [x] Add missed prop `pointsText`

Stories
- [x] Add missed prop `pointsText` to App Settings knobs

**Comment by Kosukeee** [comment]
@claudio-moya ,
https://github.com/rakuten-rex/header-rgm/commits/feature/add-points-text
