### ISSUE TITLE
'isLoggedIn' knob is not working right after clicked (supposed to reload the page)

### ISSUE THREAD

**Issue by Kosukeee** [rakuten-rex/header-rgm#39]

**Comment by Kosukeee** [comment]
@claudio-moya ,
Fixed the issue.
https://github.com/rakuten-rex/header-rgm/commits/feature/fix-isLoggedIn-konb

**Comment by claudio-moya** [comment]
reviewed and this behavior is related to `MemberMobile`  in `onSectionChange` function due to is not triggering the state update, in this case it's OK due to it has to be loggedIn or not.
