### ISSUE TITLE
CountrySettings

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/header-rgm#4]
Component
- [x] Use the following data structure for `<CountrySettings />`
```javascript
const countryList = [{
   name: 'Japan',
   key: 'jp',
}];

const languageList = [{
   name: '日本語',
   key: 'ja',
}];

const currencyList = [{
   name: 'JPY (¥)',
   key: 'jpy',
}];

<CountrySettings 
   countryList={countryList}
   languageList={languageList}
   currencyList={currencyList}
/>
```

- [x] Use same classNames postfix to map the country flags, example `United Kingdom` classname `.rm-flag-gb` -> `gb`

**Comment by Kosukeee** [comment]
- [ ] Add knobs to ContrySettings

- [ ] Add Next icon to stories

- [ ] Add ArrowIcon to stories

- [ ] Change prop name from 'list' to 'type'

- [ ] countryList -> countryType (all components)

- [ ] Check ...props

**Comment by claudio-moya** [comment]
- [ ] Update `ArrowIcon` to follow other components icons structure
https://github.com/rakuten-rex/header-rgm/blob/9ca561952fec2af7b8ad53b27928433541b7f0f7/src/ui/BeforeLogin/CountrySettings/components/ArrowIcon.jsx#L6-L11

- [ ] `NextIcon` should have `width` and `height` props here:
https://github.com/rakuten-rex/header-rgm/blob/9ca561952fec2af7b8ad53b27928433541b7f0f7/src/ui/icons/NextIcon.jsx#L11-L12

- [ ] Remove props for `NextIcon` in style
https://github.com/rakuten-rex/header-rgm/blob/9ca561952fec2af7b8ad53b27928433541b7f0f7/src/ui/BeforeLogin/CountrySettings/components/ArrowIcon.scss#L2-L3

- [ ] Use default value (ex: USA flag) instead of null
https://github.com/rakuten-rex/header-rgm/blob/9ca561952fec2af7b8ad53b27928433541b7f0f7/src/ui/BeforeLogin/CountrySettings/components/ListIcon.jsx#L42
to avoid braking the flag classname:
https://github.com/rakuten-rex/header-rgm/blob/9ca561952fec2af7b8ad53b27928433541b7f0f7/src/ui/BeforeLogin/CountrySettings/components/ListIcon.jsx#L14

- [ ] Import all countries classnames from production styles, not just a few:
https://github.com/rakuten-rex/header-rgm/blob/9ca561952fec2af7b8ad53b27928433541b7f0f7/src/ui/BeforeLogin/CountrySettings/components/ListIcon.scss#L10-L17

- [ ] Use default value for `className` in the component and add `className` to `defaultProps`
https://github.com/rakuten-rex/header-rgm/blob/9ca561952fec2af7b8ad53b27928433541b7f0f7/src/ui/BeforeLogin/CountrySettings/components/Name.jsx#L8
https://github.com/rakuten-rex/header-rgm/blob/9ca561952fec2af7b8ad53b27928433541b7f0f7/src/ui/BeforeLogin/CountrySettings/components/ListIcon.jsx#L23
https://github.com/rakuten-rex/header-rgm/blob/9ca561952fec2af7b8ad53b27928433541b7f0f7/src/ui/BeforeLogin/CountrySettings/components/ListIcon.jsx#L31

**Comment by claudio-moya** [comment]
- [ ] Add missed `return null;`
https://github.com/rakuten-rex/header-rgm/blob/c0ff96963bcc33e285608590242e2754c5d6f3e4/src/ui/BeforeLogin/CountrySettings/CountryList.jsx#L30-L32

- [ ] Remove style, this size definition should be added into each Icon component 
https://github.com/rakuten-rex/header-rgm/blob/c0ff96963bcc33e285608590242e2754c5d6f3e4/src/ui/BeforeLogin/CountrySettings/CountryList.scss#L11-L13

**Comment by claudio-moya** [comment]
- [ ] Move `Country.jsx`,  `Currency.jsx` and `Language.jsx` to `items/` folder for better code organization:
`Country.jsx` -> `items/Country.jsx`
`Currency.jsx` -> `items/Currency.jsx`
`Language.jsx` -> `items/Language.jsx`

**Comment by claudio-moya** [comment]
**Component**

- [ ] Move `src/ui/BeforeLogin/CountrySettings` to `src/ui/CountrySettings`

- [ ] Update import reference to `import CountrySettings from '../../../ui/CountrySettings';`
https://github.com/rakuten-rex/header-rgm/blob/c0ff96963bcc33e285608590242e2754c5d6f3e4/src/sections/BeforeLogin/Mobile/BeforeLogin.jsx#L7

**Stories**

- [ ] Rename `BeforeLogin/` folder stories to `CountrySettings/`

**Comment by claudio-moya** [comment]
- [ ] Exclude this countries from country list flag list:
```javascript
["an","ax","bl","bq","cu","cw","er","eu","gb-eng","gb-nir","gb-sct","gb-wls","gg","gs","im","ir","kp","me","mf","rs","sh","sj","sm","ss","sx","tk","um","xk"]
```

**Comment by claudio-moya** [comment]
Component

- [ ] Remove `before-login__` from classname 
https://github.com/rakuten-rex/header-rgm/blob/af3dc1b129fd766ae8fcbac6648305476b9748d0/src/ui/CountrySettings/CountrySettings.jsx#L23
https://github.com/rakuten-rex/header-rgm/blob/af3dc1b129fd766ae8fcbac6648305476b9748d0/src/ui/CountrySettings/CountrySettings.scss#L2

- [ ] The classname is default in `Icon.jsx`, no need to add it here, verify if this classname is used in other place, otherwise remove it
https://github.com/rakuten-rex/header-rgm/blob/af3dc1b129fd766ae8fcbac6648305476b9748d0/src/ui/CountrySettings/items/Language.jsx#L20

**Comment by claudio-moya** [comment]
- [ ] Move `.rex-flag-icon` classname into country list namespace
