### ISSUE TITLE
Enable onClick to Back button (including text)

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/header-rgm#45]

**Comment by Kosukeee** [comment]
@claudio-moya ,
Merged Mon-san's change and fixed on mobile.
https://github.com/rakuten-rex/header-rgm/commits/feature/enable-onClick-to-text

**Comment by claudio-moya** [comment]
@Kosukeee  `buttonText="Back"` should be from props instead of fixed string "Back"

**Comment by claudio-moya** [comment]
@Kosukeee thanx for the fix in Mobile
@montomos please add support to props in PC version as well

**Comment by montomos** [comment]
@claudio-moya Fixed HeaderPC.propTypes.  Please check the commit.
https://github.com/rakuten-rex/header-rgm/commit/c2c4d3960e23625d908722e8865094e4ce21c745
