### ISSUE TITLE
Create responsive header component

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/header-rgm#51]
**Component**
- [x] Create responsive version under: `src/header/HeaderResponsive.jsx`
Use the reference from here:
https://github.com/rakuten-rex/rex-header-rgm/blob/master/src/ResponsiveHeader.jsx

**Stories**

- [x] Create story and attach the reusable knobs for AppSettings

**Comment by Kosukeee** [comment]
@claudio-moya ,
Added HeaderResponsive component.
https://github.com/rakuten-rex/header-rgm/commits/feature/create-responsive-header

**Comment by claudio-moya** [comment]
I just moved the stories to the top thanx (`Header RGM/Responsive`).
Merging into develop!
