### ISSUE TITLE
Add support to form in Country, Currency and Language List

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/header-rgm#52]
Create a form wrapping the list and send the following values as hidden inputs to `https://global.rakuten.com/en/` using `POST`
![Screen Shot 2019-09-24 at 10 41 41 AM](https://user-images.githubusercontent.com/10554673/65474760-f27a6600-deb7-11e9-9436-0ebf6e94e720.png)

**Comment by Kosukeee** [comment]
@claudio-moya ,
Added form support.
https://github.com/rakuten-rex/header-rgm/commits/feature/support-form-list

**Comment by claudio-moya** [comment]
thanx! merged into develop
