### ISSUE TITLE
Fix responsive issue on proptypes

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/header-rgm#56]
![Screen Shot 2019-09-26 at 2 43 53 PM](https://user-images.githubusercontent.com/10554673/65661256-24342e00-e06c-11e9-94c8-dd7197741ba5.png)

**Comment by Kosukeee** [comment]
@claudio-moya ,
https://github.com/rakuten-rex/header-rgm/commits/feature/responsive-console-error
