### ISSUE TITLE
SectionNav

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/header-rgm#6]
**Component**

- [x] Create `SectionNav` under `src/ui/SectionNav/` to handle navigation between sections
Take reference for code structure and main styles from [UserSignUp](https://github.com/rakuten-rex/header-rgm/blob/feature/user-sign-up/src/ui/BeforeLogin/UserSignUp/Mobile/UserSignUp.jsx)
Base structure:
```jsx
<SectionNav>
   <BackButton />
   {children}
</SectionNav>
```

- [x] Remove styles in `UserSignUp.jsx` related to `div` and `BackButon`, and replace it with this code reference:
```jsx
<Fragment>
   <SignIn href={urlSignIn}>{textSignIn}</SignIn>
   <Register href={urlRegister}>{textRegister}</Register>
</Fragment>
```

**Stories**

Create the following stories under `stories/ui/SectionNav/` using this reference:

```jsx
<SectionNav>
   <BackButton />
   <div>Search Nav</div>
</SectionNav>
```

- [x] Search
- [x] BeforeLogin, import `<UserSignUp />` as children and add Knobs
- [x] AfterLogin
- [x] ShipTo
- [x] Currency
- [x] Language

**Comment by montomos** [comment]
@claudio-moya  Pushed all the changes

**Comment by claudio-moya** [comment]
Component
- [ ] Add support onClick function
https://github.com/rakuten-rex/header-rgm/blob/e21a10fcf0bd2ca04ae7ebb6fd882372cd78258b/src/ui/SectionNav/Mobile/SectionNav.jsx#L9
https://github.com/rakuten-rex/header-rgm/blob/e21a10fcf0bd2ca04ae7ebb6fd882372cd78258b/src/ui/SectionNav/Mobile/component/BackButton.jsx#L9

Stories
- [ ] Add support to `knobs actions` to test onClick, use this function on the story
https://github.com/storybookjs/storybook/tree/master/addons/actions

**Comment by montomos** [comment]
@claudio-moya Added click function.

**Comment by claudio-moya** [comment]
thanx!
