### ISSUE TITLE
[Mobile] Hide "Need help chat" and "Quick start guide"

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/header-rgm#63]
`.sticky-right-cpnbnr`

`#BotChatGoesHere`

**Comment by claudio-moya** [comment]
When menu is open hide those elements.

**Comment by Kosukeee** [comment]
@claudio-moya ,
Fixed the issue,
https://github.com/rakuten-rex/header-rgm/commits/feature/mobile-issues-rex
