### ISSUE TITLE
[Mobile] Remove extra margin-bottom (search, cart, menu button)

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/header-rgm#69]
- Change from P to SPAN
- Remove extra margin-bottom
![image](https://user-images.githubusercontent.com/10554673/65735049-9eb68980-e110-11e9-9650-797f235de396.png)

**Comment by Kosukeee** [comment]
@claudio-moya ,
Fixed in this branch.
https://github.com/rakuten-rex/header-rgm/commits/feature/mobile-issues-rex
