### ISSUE TITLE
SettingsOptions

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/header-rgm#7]
Create story 

- [x] Create component `SettingsOptions` 
```jsx

<SettingsOptions list={[]} />

...
Function:

<div>
  <SettingItem name="" value="" onClick={} />
  <SettingItem name="" value="" onClick={} />
...
</div>
```

- [x] Add onClick callback in `SettingItem` to update upper internal state
```jsx
function SettingItem({name, value, onClick}) {
return <div onClick={()=>{onClick(name, value)}}></div>
}
```

**Stories**
- [x] Create the following stories and add the sample data `CountryList, CurrencyList, LanguageList`

**Comment by claudio-moya** [comment]
**Component**
- [ ] Add unique `key` prop like `rex-setting-item-1`
https://github.com/rakuten-rex/header-rgm/blob/75f93426ba93778a2d226e0213d7701f35ef8e40/src/ui/SettingsOptions/SettingsOptions.jsx#L9

- [ ] Use `rem` instead of `px`
https://github.com/rakuten-rex/header-rgm/blob/75f93426ba93778a2d226e0213d7701f35ef8e40/src/ui/SettingsOptions/SettingItem.scss#L3-L6
https://github.com/rakuten-rex/header-rgm/blob/75f93426ba93778a2d226e0213d7701f35ef8e40/src/ui/SettingsOptions/SettingsOptions.scss#L2-L3

- [ ] Use `div` instead of `p`
```jsx
<BodyText1 tag='div'>
```

- [ ] Add validation if `name` is empty return null
https://github.com/rakuten-rex/header-rgm/blob/75f93426ba93778a2d226e0213d7701f35ef8e40/src/ui/SettingsOptions/SettingItem.jsx#L20

- [ ] Add validation if `list ` is empty return null
https://github.com/rakuten-rex/header-rgm/blob/75f93426ba93778a2d226e0213d7701f35ef8e40/src/ui/SettingsOptions/SettingsOptions.jsx#L18

**Stories**

- [ ] Add support to actions to test `onClick` function and should print `name and value`
https://github.com/storybookjs/storybook/tree/master/addons/actions

- [ ] Add support to `value` on `list` data for `Country, Language and Currency`, take example from production and the `id` values from `select`:
```
<option class="la-option" id="ja">日本語</option>
<option class="la-option" id="en">English</option>
<option class="la-option" id="zh-cn">中文(简体字)</option>
<option class="la-option" id="zh-tw">中文(繁體字)</option>
<option class="la-option" id="ko">한국어</option>
```
https://github.com/rakuten-rex/header-rgm/blob/75f93426ba93778a2d226e0213d7701f35ef8e40/stories/ui/SettingsOptions/index.jsx#L274

**Comment by claudio-moya** [comment]
- [ ] Verify how the values are send to the backend (Currency, Country, Language)

- [ ] Get the name/id of the hidden values to create a form component

- [ ] Create `CountrySettingsForm` component, add the hidden values and implement onClick functionality

**Comment by claudio-moya** [comment]
- [ ] Use `data-id` attribute instead of `id` due to it might trigger some conflicts with other elements in the pages
https://github.com/rakuten-rex/header-rgm/blob/070b317b690bc024d64077c83052d04c5221e029/src/ui/SettingsOptions/SettingItem.jsx#L15

- [ ] Use validation for string (name.trim().length > 0) instead of boolean
https://github.com/rakuten-rex/header-rgm/blob/070b317b690bc024d64077c83052d04c5221e029/src/ui/SettingsOptions/SettingItem.jsx#L7

- [ ] The component still returning a div when the list is empty, use something like:
https://github.com/rakuten-rex/header-rgm/blob/070b317b690bc024d64077c83052d04c5221e029/src/ui/SettingsOptions/SettingsOptions.jsx#L16
```jsx
if (list.length > 0) {
 return <div className={className}>{renderItems()}</div>;
}
return null;
```
- [ ] Add white background
https://github.com/rakuten-rex/header-rgm/blob/070b317b690bc024d64077c83052d04c5221e029/src/ui/SettingsOptions/SettingItem.scss#L1

**Comment by Kosukeee** [comment]
This is the json object received from BE.
https://gist.github.com/Kosukeee/3b40a9e4ef5a0757697b906aa6ea56ab

The info is coming from
```
  "pl_data": {
    "cn_tx": "Spain",
    "cn_tx_key": "es",
    "cn_gif_id": "es",
    "la_tx": "English",
    "la_tx_key": "en",
    "cu_tx": "USD ($)",
    "cu_tx_key": "usd",
```

**Comment by claudio-moya** [comment]
> This is the json object received from BE.
> https://gist.github.com/Kosukeee/3b40a9e4ef5a0757697b906aa6ea56ab
> 
> The info is coming from
> 
> ```
>   "pl_data": {
>     "cn_tx": "Spain",
>     "cn_tx_key": "es",
>     "cn_gif_id": "es",
>     "la_tx": "English",
>     "la_tx_key": "en",
>     "cu_tx": "USD ($)",
>     "cu_tx_key": "usd",
> ```
> 
> Based on this json, do I need to modify logic, right?

AWESOME

**Comment by claudio-moya** [comment]
- [ ] Add `await` to `this.submit()`
https://github.com/rakuten-rex/header-rgm/blob/7d0fc903d6f7857f50402a00e4f1a479a2694683/src/ui/SettingsOptions/SettingsForm.jsx#L33
https://github.com/rakuten-rex/header-rgm/blob/7d0fc903d6f7857f50402a00e4f1a479a2694683/src/ui/SettingsOptions/SettingsForm.jsx#L33

- [ ] Change this static url to `props` to send it from a config file to the main HOC
https://github.com/rakuten-rex/header-rgm/blob/7d0fc903d6f7857f50402a00e4f1a479a2694683/src/ui/SettingsOptions/SettingsForm.jsx#L75

- [ ] Add missed return null after if statement
https://github.com/rakuten-rex/header-rgm/blob/4e73bfcc3a3803f3b70609a244fc10a54f564390/src/ui/SettingsOptions/SettingItem.jsx#L7

**Comment by claudio-moya** [comment]
Stories

- [ ] Add `actionUrl` to Knobs as `text`
https://github.com/rakuten-rex/header-rgm/blob/49d2c51b30cf16df07122fe63e379a66466137c1/stories/ui/SettingsOptions/Components/SettingsForm.jsx#L40
