### ISSUE TITLE
[Mobile] Add space between search bar (top/bottom)

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/header-rgm#70]
![image](https://user-images.githubusercontent.com/10554673/65735100-e2a98e80-e110-11e9-80a5-815a00314202.png)

Add extra 10px to search wrapper

**Comment by claudio-moya** [comment]
Add margin to left and right too

**Comment by Kosukeee** [comment]
@claudio-moya ,
Fixed in this branch.
https://github.com/rakuten-rex/header-rgm/commits/feature/mobile-issues-rex
