### ISSUE TITLE
[Mobile] LoggedIn user state is not aligned correctly (missing 'align-items: center')

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/header-rgm#71]
![image](https://user-images.githubusercontent.com/10554673/65735172-33b98280-e111-11e9-9e25-1034fa408c2c.png)

**Comment by claudio-moya** [comment]
Add padding-top 10px to wrapper

**Comment by Kosukeee** [comment]
@claudio-moya ,
Fixed in this branch.
https://github.com/rakuten-rex/header-rgm/commits/feature/mobile-issues-rex
